#!/bin/sh
set -e

git fetch origin
if ! cmp -s -- ~/.gitconfig config; then
    cp ~/.gitconfig config
    git add config && git commit -m'tmp'
    git reset --hard HEAD~
fi
git merge FETCH_HEAD --ff-only
cp config ~/.gitconfig
